<?php
/**
 * @file
 * The main module file for the islandora_solr_metadata module.
 */

/**
 * Implements hook_menu().
 */
function islandora_solr_metadata_menu() {
  $items = array();
  $items['admin/islandora/search/islandora_solr/metadata'] = array(
    'title' => 'Metadata Display',
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_solr_metadata_admin_form'),
    'access arguments' => array('administer islandora_solr_metadata'),
    'file' => 'includes/admin.inc',
  );
  $items['admin/islandora/search/islandora_solr_metadata/config/%'] = array(
    'title callback' => 'islandora_solr_metadata_display_configuration_name',
    'title arguments' => array(5),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_solr_metadata_config_form', 5),
    'access callback' => 'islandora_solr_metadata_access',
    'access arguments' => array(5),
    'file' => 'includes/config.inc',
  );
  $items['admin/islandora/search/islandora_solr_metadata/config/delete/%'] = array(
    'title' => 'Delete display configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_solr_metadata_delete_config_form', 6),
    'access callback' => 'islandora_solr_metadata_access',
    'access arguments' => array(6),
    'file' => 'includes/delete.inc',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function islandora_solr_metadata_theme() {
  return array(
    'islandora_solr_metadata_management_table' => array(
      'render element' => 'table',
      'file' => 'theme/theme.inc',
    ),
    'islandora_solr_metadata_display' => array(
      'template' => 'theme/islandora-solr-metadata-display',
      // We can add PIDs to the end of this pattern in our preprocess function
      // and templates will be able to have have a pid appended to the
      // template name to overide a template on a per object basis.
      // An example template might be named:
      // "islandora-solr-metadata-display--islandora-27.tpl.php".
      'pattern' => 'islandora_solr_metadata_display__',
      'variables' => array('islandora_object' => NULL),
      'file' => 'theme/theme.inc',
    ),
  );
}

/**
 * Implements hook_permission().
 */
function islandora_solr_metadata_permission() {
  return array(
    'administer islandora_solr_metadata' => array(
      'title' => 'Create and manage metadata display configurations',
    ),
  );
}

/**
 * Access callback for accessing a configuration based upon ID.
 *
 * @param int $configuration_id
 *   The configuration ID of the list we are accessing.
 *
 * @return bool
 *   TRUE if the user has permission and the list exists, FALSE otherwise.
 */
function islandora_solr_metadata_access($configuration_id) {
  module_load_include('inc', 'islandora_solr_metadata', 'includes/db');
  return islandora_solr_metadata_configuration_exists($configuration_id) && user_access('administer islandora_solr_metadata');
}

/**
 * Title callback for the configuration display.
 *
 * @param int $configuration_id
 *   The ID of the configuration we are retrieving the name of.
 *
 * @return string
 *   The name of the configuration that is to be edited.
 */
function islandora_solr_metadata_display_configuration_name($configuration_id) {
  module_load_include('inc', 'islandora_solr_metadata', 'includes/db');
  $configuration_name = islandora_solr_metadata_retrieve_configuration_name($configuration_id);
  return format_string('@configuration_name display configuration', array('@configuration_name' => $configuration_name));
}

/**
 * Implements hook_i18n_string_info().
 */
function islandora_solr_metadata_i18n_string_info() {
  return array(
    'islandora_solr_metadata' => array(
      'title' => t('Islandora Solr Metadata'),
      'description' => t('Translatable configuration names and display labels.'),
      'format' => FALSE,
      'list' => TRUE,
    ),
  );
}

/**
 * Implements hook_islandora_metadata_display_info().
 */
function islandora_solr_metadata_islandora_metadata_display_info() {
  return array(
    'islandora_solr_metadata' => array(
      'label' => t('Islandora Solr Metadata'),
      'description' => t('Metadata display driven by the Islandora Solr Search module'),
      'callback' => 'islandora_solr_metadata_display_callback',
      'configuration' => 'admin/islandora/search/islandora_solr/metadata',
    ),
  );
}

/**
 * Metadata display callback for rendering metadata from Solr.
 *
 * @param AbstractObject $object
 *   An AbstractObject representing an object within Fedora.
 *
 * @return string
 *   Markup representing the metadata display pulled from Solr.
 */
function islandora_solr_metadata_display_callback(AbstractObject $object) {
  $elements = array(
    'islandora_object' => $object,
  );
  return theme('islandora_solr_metadata_display', $elements);
}
